language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r src/requirements.txt
# command to run tests
script:
  - cd src
  - tox
  - pytest # or py.test for Python versions 3.5 and below
  
